"""Update task model for family assignment

Revision ID: df607578f7ed
Revises: 5b14f6bc5356
Create Date: 2025-08-18 07:16:51.054294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df607578f7ed'
down_revision: Union[str, Sequence[str], None] = '5b14f6bc5356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], name='fk_task_completions_member_id'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_task_completions_task_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completions_id'), 'task_completions', ['id'], unique=False)

    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_completion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_points_history_task_completions', 'task_completions', ['task_completion_id'], ['id'])
        batch_op.drop_column('task_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('assigned_to_id', existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('assigned_to_id', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_points_history_task_completions', type_='foreignkey')
        batch_op.create_foreign_key('fk_points_history_tasks', 'tasks', ['task_id'], ['id'])
        batch_op.drop_column('task_completion_id')

    op.drop_index(op.f('ix_task_completions_id'), table_name='task_completions')
    op.drop_table('task_completions')
    # ### end Alembic commands ###